site_name:        NPFinancial.jl
repo_url:         https://github.com/tk3369/NPFinancial.jl
site_description: Financial library
site_author:      tk3369

theme:
  name: 'material'

# extra_css:
#   - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

# nav:
#   - Home: index.md
